server:
  port: 8080

spring:
  datasource:
    url: ${youngflix_DB_URL:jdbc:mysql://localhost:3306/youngflix?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${youngflix_DB_USERNAME:root}
    password: ${youngflix_DB_PASSWORD:dnjswnsdud1.}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE

auth:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

spring.config.import: optional:.env